/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pengaduan_app.gui;

import com.mycompany.pengaduan_app.model.Pengaduan;
import com.mycompany.pengaduan_app.model.User;
import com.mycompany.pengaduan_app.service.PengaduanService;
import com.mycompany.pengaduan_app.util.ThreadUtil;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author FAUZI
 */
public class AdminDashboard1 extends javax.swing.JFrame {

    private User currentUser;
    private PengaduanService pengaduanService;
    private ResourceBundle messages;
    private DefaultTableModel tableModel;
    private List<Pengaduan> pengaduanList;

    /**
     * Creates new form AdminDashboard1
     */
    public AdminDashboard1() {
        initComponents();
    }

    public AdminDashboard1(User user) {
        this.currentUser = user;
        this.pengaduanService = new PengaduanService();
        this.messages = ResourceBundle.getBundle("messages", Locale.getDefault());
        initComponents();
        initTable();
        loadData();
        translateComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        updateStatusButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        refreshButton.setText("ref");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        updateStatusButton.setText("update ststus");
        updateStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStatusButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(refreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(updateStatusButton)
                    .addComponent(refreshButton))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColorBackgoundHead(new java.awt.Color(0, 153, 204));
        table.setColorBordeFilas(new java.awt.Color(242, 242, 242));
        table.setColorBordeHead(new java.awt.Color(242, 242, 242));
        table.setColorFilasForeground1(new java.awt.Color(0, 153, 204));
        table.setColorFilasForeground2(new java.awt.Color(0, 153, 204));
        jScrollPane2.setViewportView(table);
        table.setRowHeight(30);  // Menentukan tinggi baris 30 piksel

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void updateStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStatusButtonActionPerformed
        // TODO add your handling code here:
        updateStatusAction(evt);
    }//GEN-LAST:event_updateStatusButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        logoutAction(evt);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void initTable() {
        String[] columnNames = {"Judul", "Kategori", "Status", "Tanggal Buat", "Deskripsi"};
        tableModel = new DefaultTableModel(columnNames, 0); // 0 = jumlah baris awal
        table.setModel(tableModel);
    }

    private void translateComponents() {
        refreshButton.setText(messages.getString("refresh.button"));
        logoutButton.setText(messages.getString("logout.button"));
        updateStatusButton.setText(messages.getString("pengaduan.update.status"));
    }

    private void loadData() {
        ThreadUtil.runAsync(() -> pengaduanService.getAllPengaduan())
                .thenAccept(list -> SwingUtilities.invokeLater(() -> {
            this.pengaduanList = list;
            tableModel.setRowCount(0);
            for (Pengaduan p : list) {
                tableModel.addRow(new Object[]{
                    p.getJudul(), p.getKategori(), p.getStatus(),
                    p.getTanggalBuat().toString(), p.getDeskripsi()
                });
            }
        }));
    }

    private void updateStatusAction(ActionEvent e) {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, messages.getString("admin.select.pengaduan"));
            return;
        }

        Pengaduan selected = pengaduanList.get(selectedRow);

        String[] statuses = {"BELUM", "PROSES", "SELESAI"};
        String newStatus = (String) JOptionPane.showInputDialog(
                this, messages.getString("pengaduan.select.status"),
                messages.getString("pengaduan.update.status"),
                JOptionPane.QUESTION_MESSAGE, null, statuses, selected.getStatus()
        );

        if (newStatus != null && !newStatus.equals(selected.getStatus())) {
            String response = JOptionPane.showInputDialog(
                    this, messages.getString("pengaduan.response"), ""
            );

            ThreadUtil.runAsync(() -> {
                pengaduanService.updateStatus(selected.getId(), newStatus, response);
                return null;
            }).thenRun(() -> SwingUtilities.invokeLater(this::loadData));
        }
    }

    private void logoutAction(ActionEvent e) {
        dispose();
        new LoginFrame().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton refreshButton;
    private rojeru_san.complementos.RSTableMetro table;
    private javax.swing.JButton updateStatusButton;
    // End of variables declaration//GEN-END:variables
}
