/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pengaduan_app.gui;

import com.mycompany.pengaduan_app.model.Pengaduan;
import com.mycompany.pengaduan_app.model.User;
import com.mycompany.pengaduan_app.service.PengaduanService;
import com.mycompany.pengaduan_app.util.ThreadUtil;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author FAUZI
 */
public class UserDashboard1 extends javax.swing.JFrame {

    private User currentUser;
    private PengaduanService pengaduanService;
    private ResourceBundle messages;
    private DefaultTableModel tableModel;

    /**
     * Creates new form UserDashboard1
     */
    public UserDashboard1() {
        initComponents();
    }

    public UserDashboard1(User user) {
        this.currentUser = user;
        this.pengaduanService = new PengaduanService();
        this.messages = ResourceBundle.getBundle("messages", Locale.getDefault());
        initComponents(); 
        this.tableModel = (DefaultTableModel) table.getModel(); // ambil model dari table
        translateComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); //full screen

        loadData(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane3 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojeru_san.complementos.RSTableMetro();
        topPanel = new javax.swing.JPanel();
        newPengaduanButton = new rojeru_san.complementos.RSButtonHover();
        refreshButton = new rojeru_san.complementos.RSButtonHover();
        logoutButton = new rojeru_san.complementos.RSButtonHover();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new rojeru_san.complementos.RSTableMetro();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(rSTableMetro1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newPengaduanButton.setBackground(new java.awt.Color(0, 153, 204));
        newPengaduanButton.setText("new");
        newPengaduanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPengaduanButtonActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(0, 153, 204));
        refreshButton.setText("refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(0, 153, 204));
        logoutButton.setText("new");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(newPengaduanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPengaduanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jScrollPane2, java.awt.BorderLayout.LINE_END);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColorBackgoundHead(new java.awt.Color(0, 153, 204));
        table.setColorBordeFilas(new java.awt.Color(242, 242, 242));
        table.setColorBordeHead(new java.awt.Color(242, 242, 242));
        table.setColorFilasForeground1(new java.awt.Color(0, 153, 204));
        table.setColorFilasForeground2(new java.awt.Color(0, 153, 204));
        table.setColorSelBackgound(new java.awt.Color(0, 153, 204));
        jScrollPane4.setViewportView(table);
        table.getColumnModel().getColumn(0).setPreferredWidth(200); // Menentukan lebar kolom pertama
        table.getColumnModel().getColumn(1).setPreferredWidth(150); // Menentukan lebar kolom kedua
        table.setRowHeight(30);  // Menentukan tinggi baris 30 piksel

        getContentPane().add(jScrollPane4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPengaduanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPengaduanButtonActionPerformed
        // TODO add your handling code here:  
        newPengaduanAction(evt);
    }//GEN-LAST:event_newPengaduanButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refreshData();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        logoutAction(evt);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void translateComponents() {
        newPengaduanButton.setText(messages.getString("pengaduan.new"));
        refreshButton.setText(messages.getString("refresh.button"));
        logoutButton.setText(messages.getString("logout.button"));

        tableModel = new DefaultTableModel(new Object[][]{}, new Object[]{
            messages.getString("pengaduan.judul"),
            messages.getString("pengaduan.kategori"),
            messages.getString("pengaduan.status"),
            messages.getString("pengaduan.tanggal")
        });
        table.setModel(tableModel);
    }

    private void loadData() {
        ThreadUtil.runAsync(() -> pengaduanService.getPengaduanByUser(currentUser.getId()))
                .thenAccept(pengaduanList -> SwingUtilities.invokeLater(() -> {
            tableModel.setRowCount(0);
            for (Pengaduan p : pengaduanList) {
                tableModel.addRow(new Object[]{
                    p.getJudul(), p.getKategori(), p.getStatus(),
                    p.getTanggalBuat().toString()
                });
            }
        }));
    }

    private void newPengaduanAction(ActionEvent e) {
        new PengaduanForm1(currentUser, this).setVisible(true);
    }

    private void logoutAction(ActionEvent e) {
        dispose();
        new LoginFrame().setVisible(true);
    }

    public void refreshData() {
        loadData();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private rojeru_san.complementos.RSButtonHover logoutButton;
    private rojeru_san.complementos.RSButtonHover newPengaduanButton;
    private rojeru_san.complementos.RSTableMetro rSTableMetro1;
    private rojeru_san.complementos.RSButtonHover refreshButton;
    private rojeru_san.complementos.RSTableMetro table;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
